services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3322:3306" # Expose MySQL port
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh # Mount init script
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql # Mount SQL script
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "chmod +x /docker-entrypoint-initdb.d/init_db.sh && /docker-entrypoint-initdb.d/init_db.sh && docker-entrypoint.sh mysqld",
      ]
    networks:
      - geth-net
    #restart: always

  geth:
    image: ethereum/client-go:v1.11.6
    container_name: geth-node
    environment:
      GETH_PASSWORD: 123456
    volumes:
      - ./genesis.json:/root/genesis.json
      - geth-data:/root/.ethereum
      - ./init-genesis.sh:/root/init-genesis.sh
      - ./keystore:/root/.ethereum/keystore # Mount the keystore files
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "chmod +x /root/init-genesis.sh && /root/init-genesis.sh",
      ]
    ports:
      - "8545:8545"
    networks:
      - geth-net

  # web-app:
  #   build:
  #     context: .
  #   container_name: web-app
  #   depends_on:
  #     - geth
  #     - mysql
  #   environment:
  #     - INFURA_URL=http://geth:8545
  #     - DB_URL=mysql:3322
  #     - PRIVATE_KEY=0xc81786c23e512324ed9b544ad8b7cdfc629e1651
  #   ports:
  #     - "8080:8080" # Web app exposed on port 8080
  #   networks:
  #     - geth-net

networks:
  geth-net:
    name: application_geth-net
    driver: bridge

volumes:
  mysql-data:
  geth-data:
